export const SET_APP_STATE = 'SET_APP_STATE';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const SET_AUTH_STATE = 'SET_AUTH_STATE';
export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const SET_USER_CREDENTIAL = 'SET_USER_CREDENTIAL';
export const CONNECTED_CLIENTS = 'CONNECTED_CLIENTS';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_ACTIVE_WINDOW = 'SET_ACTIVE_WINDOW';
export const MAP_USER_ID_NAME = 'MAP_USER_ID_NAME';
export const CLIENTS_DETAILS = 'CLIENTS_DETAILS';

